// version_generated.go is autogenerated from version.go by running "go generate":
//go:generate sh -c "sed -e /@REMOVE@/d -e s/@DATE@/`date +%Y%m%d`/ version.go > version_generated.go"

package zboxmobile

/* @REMOVE@
const (
	VERSION = "0.@DATE@"
)
@REMOVE@ */

// eof
